# This file was generated by GoReleaser. DO NOT EDIT.
cask "well" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "ec1ae6950fe5ec5a6ba2d0c7a27457c30541a4052d12f9b74664b26b9b80a63a"
      url "https://github.com/WellApp-ai/platform/releases/download/v#{version}/well_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8c082a9e6e630fd1eb2cbc124e238a80fe0c2cec0312ac2bed536d79ad3a0571"
      url "https://github.com/WellApp-ai/platform/releases/download/v#{version}/well_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b9750af0918b4cf677e6908e9872ce3473e3bb1270dfd59a54a5ac94349c56ae"
      url "https://github.com/WellApp-ai/platform/releases/download/v#{version}/well_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7bf390c6d1dd74da9870703c56bf6143bee0b776d675e5ffa71fcf71d3f8ab50"
      url "https://github.com/WellApp-ai/platform/releases/download/v#{version}/well_#{version}_linux_arm64.tar.gz"
    end
  end

  name "well"
  desc "Well — your finance copilot, from the shell"
  homepage "https://wellapp.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "well"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/well"]
  end

  # No zap stanza required

end
