# This file was generated by GoReleaser. DO NOT EDIT.
cask "well" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "3e4936f4379fccdff1420203b04ef572efc71d6c5117fb45cb6218f2358de821"
      url "https://github.com/WellApp-ai/homebrew-tap/releases/download/v#{version}/well_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e370eda1edb77e772679b4532babf2cfc56f089d9740db42c194d657753402ae"
      url "https://github.com/WellApp-ai/homebrew-tap/releases/download/v#{version}/well_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "334b36446b50c29e7662645272126e7407be7653e812c5923c4207486c6c5164"
      url "https://github.com/WellApp-ai/homebrew-tap/releases/download/v#{version}/well_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "37582bc25591f9413a190f2151dfdf6e10b5ed2fb5e8823ee7852f413cf37741"
      url "https://github.com/WellApp-ai/homebrew-tap/releases/download/v#{version}/well_#{version}_linux_arm64.tar.gz"
    end
  end

  name "well"
  desc "Well — your finance copilot, from the shell"
  homepage "https://wellapp.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "well"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/well"]
  end

  # No zap stanza required

end
