# This file was generated by GoReleaser. DO NOT EDIT.
cask "well-staging" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "500c3979f2074159e202f4caf5562bdeca8027dc473cfda744c8b943ae0455b0"
      url "https://github.com/WellApp-ai/homebrew-tap/releases/download/v#{version}/well-staging_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "90ea5c3b7e96f244cfdd8c01b0b64bfa3ab177520effef7bb9d69603f05418db"
      url "https://github.com/WellApp-ai/homebrew-tap/releases/download/v#{version}/well-staging_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "79c3888098bb144140a828e307aaded97b826013ebfa436269cf772c29082a5a"
      url "https://github.com/WellApp-ai/homebrew-tap/releases/download/v#{version}/well-staging_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bab831d57eae0d23a2642b8c9a73f03cf2138aa334c35cbe658dcf0a579a2051"
      url "https://github.com/WellApp-ai/homebrew-tap/releases/download/v#{version}/well-staging_#{version}_linux_arm64.tar.gz"
    end
  end

  name "well-staging"
  desc "Well CLI (staging) — targets the test API by default"
  homepage "https://wellapp.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "well-staging"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/well-staging"]
  end

  # No zap stanza required

end
