# This file was generated by GoReleaser. DO NOT EDIT.
cask "well-staging" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "a5e722a7ded5010271d101e3a66f7aeb44e5b4ccd7ae2f639b46aea612650aa6"
      url "https://github.com/WellApp-ai/platform/releases/download/v#{version}/well-staging_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ecd6199a7ed91bcfcacb9d1eb219980a34083c75fbea121ecf4fd4ea49aea991"
      url "https://github.com/WellApp-ai/platform/releases/download/v#{version}/well-staging_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "05ec7885a1860c382042e6e16f76f992422fe4da566a9f874f401dedfdd62ec3"
      url "https://github.com/WellApp-ai/platform/releases/download/v#{version}/well-staging_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "394ff207e3b1d7381ff742ca1148ecda3a6ec04dea1bb614fa50c6e9990a8a38"
      url "https://github.com/WellApp-ai/platform/releases/download/v#{version}/well-staging_#{version}_linux_arm64.tar.gz"
    end
  end

  name "well-staging"
  desc "Well CLI (staging) — targets the test API by default"
  homepage "https://wellapp.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "well-staging"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/well-staging"]
  end

  # No zap stanza required

end
